version: "3.9"

services:
  reference:
    image: postgres:16.2-alpine3.19
    container_name: reference
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo
    ports:
      - 5432:5432
    restart: always

  target:
    image: postgres:16.2-alpine3.19
    container_name: target
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo
    ports:
      - 5433:5432
    restart: always

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - target
      - reference
    ports:
      - 8080:8080
